### ISSUE TITLE
Hyperlinks within `http://dafny.org/dafny` appear to 404

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/dafny-lang.github.io#14]
Wasn't sure if this was a deploy issue or a problem with the website generation, so I didn't propose out a fix, but: http://dafny.org/dafny/ comes up in search results for the Dafny Reference, and the URLs it points to 404.  For instance,

```
➜  ~ curl -svo /dev/null http://dafny.org/dafny/latest/DafnyRef/DafnyRef
*   Trying 185.199.110.153...
* TCP_NODELAY set
* Connected to dafny.org (185.199.110.153) port 80 (#0)
> GET /dafny/latest/DafnyRef/DafnyRef HTTP/1.1
> Host: dafny.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
➜  ~ curl -svo /dev/null http://dafny.org/latest/DafnyRef/DafnyRef
*   Trying 185.199.110.153...
* TCP_NODELAY set
* Connected to dafny.org (185.199.110.153) port 80 (#0)
> GET /latest/DafnyRef/DafnyRef HTTP/1.1
> Host: dafny.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
```

The formatting for that page appears to be wonky, too, perhaps because of a bad css URL, maybe?

**Comment by davidcok** [comment]
Appears to have been resolved by GitHub markdown rebuilds since then.

**Comment by fabiomadge** [comment]
I agree that the 404 is resolved, but I don't understand why this is not in sync with dafny.org.

**Comment by davidcok** [comment]
It was decided (cf. Robin if you have questions) to have the documentation on dafny.org be in sync with the releases.
So under dafny.org is dafny.org/v3.9.0, dafny.org/v3.9.1, dafny.org/v3.10.0, and dafny.org/latest, which is the same as dafny.org/v3.10.0 right now.  These are snapshots of documentation at release time. The script for doing snapshots is still being debugged a bit, hence the problem we just had

dafny.org/dafny remains a link to the bleeding-edge development for documentation.

**Comment by fabiomadge** [comment]
My point is that dafny.org/index.html is more recent than dafny.org/dafny/index.html. The `dafny-lang/dafny` version has huge images and is laid out differently.

**Comment by davidcok** [comment]
Ah. Clement did some work to make dafny.org/index.html mobile-friendly. I'll back port that to dafny.org/dafny. Thanks.
